import prisma from "@/lib/prisma";
import { llm } from "@/lib/llm";

export async function summarizeDocumentJob(documentId: string, extractedText: string) {
  try {
    // 1. Mark as generating
    await prisma.document.update({
      where: { id: documentId },
      data: { summaryStatus: "GENERATING" },
    });

    if (!extractedText || extractedText.trim() === "") {
      await prisma.document.update({
        where: { id: documentId },
        data: { summaryStatus: "FAILED", summary: "No text could be extracted to summarize." },
      });
      return;
    }

    console.log("--- SUMMARIZE JOB DEBUG ---");
    console.log("process.env.LLM_PROVIDER inside summarize job is:", process.env.LLM_PROVIDER);
    
    // 2. Call Ollama (or future Gemini)
    let summary = await llm.summarize(extractedText);

    // Strip common meta-preambles generated by LLMs as a safety net
    console.log("--- BEFORE STRIPPING ---");
    console.log(summary);

    // Use 's' flag so .* can match across newlines if needed, or just match until the first double newline
    summary = summary.replace(/^(?:Here(?:'s| is) (?:a |an )?(?:\d+-sentence )?summary[^\n]*:\s*)/i, "").trim();
    summary = summary.replace(/^(?:This (?:is a |document )[^\n]*:\s*)/i, "").trim();
    summary = summary.replace(/^(?:Summary:\s*)/i, "").trim();
    
    // Catch-all for bolded preambles like "**Summary:**"
    summary = summary.replace(/^\*\*Summary:?\*\*\s*/i, "").trim();

    console.log("--- AFTER STRIPPING ---");
    console.log(summary);

    // 3. Save to DB
    await prisma.document.update({
      where: { id: documentId },
      data: { summaryStatus: "DONE", summary },
    });
  } catch (error) {
    console.error(`[Summarization Job Error] Doc ${documentId}:`, error);
    
    // 4. Mark as failed
    await prisma.document.update({
      where: { id: documentId },
      data: { summaryStatus: "FAILED", summary: null },
    }).catch(e => console.error("Failed to update status to FAILED", e));
  }
}
